26/08/2024

Esdras Lara Magaña, 752312

# A03-Phyton

1. Toma el archivo datosCT.xlsx

In [5]:
import pandas as pd
datos = pd.read_excel("datosCT.xlsx")
datos

Unnamed: 0  Ingreso  Gasto
0        Enero     1340   1880
1      Febrero     2590   3130
2        Marzo     3570   2140
3        Abril     4450   3370
4         Mayo     1330   2990
5        Junio     1610   1970
6        Julio     1500   2230
7       Agosto     2270   1240
8   Septiembre     1910   1470
9      Octubre     2120   2280
10   Noviembre     3950   1870
11   Diciembre     1380   3140

* Calcula la Utilidad (Ingreso - Gasto)

In [14]:
datos["Utilidad"] = datos["Ingreso"] - datos["Gasto"]
datos

Unnamed: 0  Ingreso  Gasto  Utilidad
0        Enero     1340   1880      -540
1      Febrero     2590   3130      -540
2        Marzo     3570   2140      1430
3        Abril     4450   3370      1080
4         Mayo     1330   2990     -1660
5        Junio     1610   1970      -360
6        Julio     1500   2230      -730
7       Agosto     2270   1240      1030
8   Septiembre     1910   1470       440
9      Octubre     2120   2280      -160
10   Noviembre     3950   1870      2080
11   Diciembre     1380   3140     -1760

* Encuentra el promedio de Gastos en los meses que la Utilidad fue negativa

In [25]:
util_neg = datos[datos["Utilidad"]<0]
promedio_util_neg = util_neg["Gasto"].mean()
promedio_util_neg

2517.1428571428573

* Encuentra los ingresos totales del año

In [28]:
ingresos_totales = datos["Ingreso"].sum()
ingresos_totales

28020

2. Crea las siguientes estructuras usando numpy:

In [33]:
import numpy as np
A = np.array ([
    [1,2],
    [3,4]
])
A

array([[1, 2],
       [3, 4]])

In [35]:
b = np.array ([
    [2],
    [4]
])
b

array([[2],
       [4]])

In [39]:
R = A*b
R

array([[ 2,  4],
       [12, 16]])